name: Deploy Sepolia

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
      UNISWAP_ROUTER: ${{ secrets.UNISWAP_ROUTER }}
      WETH: ${{ secrets.WETH }}
      POOL_FEE: ${{ secrets.POOL_FEE }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Compile
        run: npx hardhat compile

      - name: Deploy to Sepolia
        run: npx hardhat deploy --tags sepolia --network sepolia

      - name: Upload deployments
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deployments-sepolia
          path: deployments/sepolia
          if-no-files-found: warn
